/**
 * 科技新闻来源（仅新闻站 RSS）
 * 垂直媒体（量子位/雷锋网等）改由热点频道采集
 */
module.exports = [
  // ===== 海外 AI 源 =====
  { id: "openai", name: "OpenAI", url: "https://openai.com/blog/rss.xml", filter: true },
  { id: "google-ai", name: "Google AI", url: "https://blog.google/technology/ai/rss/", filter: true },
  { id: "huggingface", name: "Hugging Face", url: "https://huggingface.co/blog/feed.xml", filter: true },
  { id: "techcrunch-ai", name: "TechCrunch AI", url: "https://techcrunch.com/category/artificial-intelligence/feed/", filter: true },
  { id: "verge-ai", name: "The Verge AI", url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml", filter: true },
  { id: "mit-tr", name: "MIT Tech Review", url: "https://www.technologyreview.com/feed/", filter: true },
  { id: "hn-ai", name: "Hacker News", url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+GPT+OR+Claude+OR+Codex+OR+Agent+OR+OpenAI+OR+Anthropic+OR+Gemini", filter: true },
  { id: "ars", name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index", filter: true },
  { id: "github-blog", name: "GitHub Blog", url: "https://github.blog/feed/", filter: true },

  // ===== 中文综合科技新闻站 =====
  { id: "solidot", name: "Solidot", url: "https://www.solidot.org/index.rss", filter: true },
  { id: "kr36", name: "36氪", url: "https://36kr.com/feed", filter: true },
  { id: "ithome", name: "IT之家", url: "https://www.ithome.com/rss/", filter: true }
];

/** 已迁到热点频道的 sourceId，新闻列表需剔除 */
module.exports.HOT_ONLY_SOURCE_IDS = [
  "qbitai",
  "leiphone",
  "ifanr",
  "jiemian",
  "jiqizhixin",
  "sspai",
  "qbitai-hot",
  "leiphone-hot",
  "ifanr-hot",
  "sspai-hot",
  "kr36-video",
  "jiqizhixin-hot",
  "jiemian-hot"
];

/** 过于日常/泛化，不进词云 */
module.exports.GENERIC_TERMS = [
  "ai",
  "a.i.",
  "artificial intelligence",
  "人工智能",
  "科技",
  "智能",
  "互联网",
  "软件",
  "数据",
  "代码",
  "编程",
  "手机",
  "电脑",
  "数码",
  "开源",
  "github",
  "论文",
  "技术",
  "创新",
  "未来",
  "公司",
  "产品",
  "用户",
  "平台",
  "内容",
  "机器人",
  // 词云额外排除的宽泛科技术语
  "llm",
  "llms",
  "large language model",
  "大模型",
  "大语言模型",
  "语言模型",
  "基座模型",
  "foundation model",
  "深度学习",
  "deep learning",
  "神经网络",
  "neural network",
  "机器学习",
  "machine learning",
  "自然语言处理",
  "nlp",
  "computer vision",
  "计算机视觉",
  "transformer",
  "attention",
  "gpu",
  "tpu",
  "npu",
  "算力",
  "芯片",
  "模型",
  "算法",
  "框架",
  "系统",
  "应用",
  "研究",
  "training",
  "inference",
  "推理",
  "训练",
  "微调",
  "预训练",
  "fine-tuning",
  "pretraining",
  "prompt",
  "prompts",
  "token",
  "tokens",
  "embedding",
  "embeddings",
  "dataset",
  "datasets",
  "benchmark",
  "arxiv",
  "www",
  "python",
  "javascript",
  "typescript",
  "java",
  "rust",
  "go",
  "c++",
  "openapi",
  "api",
  "sdk",
  "plugin",
  "plugins",
  "agent",
  "agents",
  "智能体",
  "自动驾驶",
  "具身智能",
  "强化学习",
  "reinforcement learning",
  "cnn",
  "rnn",
  "lstm"
];

/** 营销/非术语噪声 */
module.exports.NOISE_TERMS = [
  "关注",
  "公众号",
  "微信",
  "欢迎",
  "订阅",
  "官网",
  "邀请",
  "视频号",
  "点赞",
  "转发",
  "留言",
  "私信",
  "扫码",
  "广告",
  "活动",
  "抽奖"
];

/** 词云白名单：专科实体 / 模型 / 公司 / 算法 */
module.exports.SPECIFIC_TERMS = [
  // 大模型 / 产品
  "llm",
  "llms",
  "large language model",
  "大模型",
  "大语言模型",
  "gpt",
  "gpt-4",
  "gpt-5",
  "claude",
  "gemini",
  "chatgpt",
  "deepseek",
  "llama",
  "mistral",
  "qwen",
  "通义千问",
  "文心一言",
  "kimi",
  "豆包",
  "混元",
  "sora",
  "midjourney",
  "stable diffusion",
  "dall-e",
  "flux",
  "copilot",
  "cursor",
  "codex",
  // 方法 / 概念
  "rag",
  "检索增强",
  "rlhf",
  "dpo",
  "transformer",
  "attention",
  "multimodal",
  "多模态",
  "agentic",
  "智能体",
  "multi-agent",
  "多智能体",
  "function calling",
  "提示工程",
  "prompt engineering",
  "模型蒸馏",
  "模型量化",
  "长上下文",
  "context window",
  "world model",
  "世界模型",
  "具身智能",
  "embodied",
  "自动驾驶",
  "fsd",
  "人形机器人",
  "humanoid",
  // 深度学习
  "深度学习",
  "deep learning",
  "神经网络",
  "强化学习",
  "reinforcement learning",
  "cnn",
  "rnn",
  "lstm",
  "nlp",
  "自然语言处理",
  "computer vision",
  "计算机视觉",
  // 公司
  "openai",
  "anthropic",
  "深度求索",
  "google deepmind",
  "deepmind",
  "meta ai",
  "xai",
  "grok",
  "智谱",
  "月之暗面",
  "百川智能",
  "零一万物",
  "minimax",
  "科大讯飞",
  "讯飞星火",
  "商汤",
  "旷视",
  "第四范式",
  "阶跃星辰",
  "面壁智能",
  "hugging face",
  "nvidia",
  "英伟达",
  // 硬件 / 设施
  "gpu",
  "tpu",
  "npu",
  "h100",
  "h200",
  "b100",
  "b200",
  "a100",
  "昇腾",
  "寒武纪",
  "算力集群",
  "向量数据库",
  "知识图谱",
  "graphrag",
  "modelscope",
  "魔搭",
  "arxiv",
  // 顶会
  "neurips",
  "icml",
  "iclr",
  "cvpr",
  "acl",
  "emnlp",
  "aaai",
  "ijcai",
  "siggraph",
  "iccv",
  "eccv",
  "kdd",
  "www",
  "icme"
];

/** 新闻过滤用（保留较宽） */
module.exports.KEYWORDS = [
  ...module.exports.GENERIC_TERMS,
  ...module.exports.SPECIFIC_TERMS,
  "语言模型",
  "基座模型",
  "foundation model",
  "预训练",
  "微调",
  "alignment",
  "推理模型",
  "token",
  "tokens",
  "prompt",
  "prompts",
  "agent",
  "agents",
  "tool use",
  "插件",
  "plugin",
  "plugins",
  "skill",
  "skills",
  "视觉模型",
  "语音模型",
  "代码生成",
  "视频生成",
  "文生图",
  "文生视频",
  "图生视频",
  "neural network",
  "迁移学习",
  "自监督",
  "无监督",
  "语义理解",
  "文本生成",
  "机器翻译",
  "情感分析",
  "microsoft ai",
  "生数科技",
  "爱诗科技",
  "ai手机",
  "ai pc",
  "ai眼镜",
  "ai硬件",
  "ai芯片",
  "ai安全",
  "ai治理",
  "ai伦理",
  "ai搜索",
  "ai编程",
  "ai写作",
  "ai绘画",
  "ai音乐",
  "ai教育",
  "ai医疗",
  "ai金融",
  "ai法律",
  "算力",
  "数据中心",
  "open source",
  "芯片",
  "半导体",
  "华为",
  "小米",
  "苹果",
  "特斯拉",
  "5g",
  "6g",
  "卫星",
  "量子"
];

module.exports.DEDUP_THRESHOLD = 0.55;
